# samsung_tv_remote (AA59-00741A)
# path: /storage/.config/rc_keymaps/samsung_tv_remote.toml
# NOTE: special keys should have no mapping in kodi (KEY_F1, ...)
#       check Lircmap.xml and remote.xml for reference
[[protocols]]
name = "samsung_tv_remote"
protocol = "nec"
variant = "necx"

# SPECIAL KEYS to use with irexec -d /storage/.config/lircrc
# KEY_F6: call rest-api: power tv on
# KEY_F5: load alternate keymap (inhibit kodi control)

[protocols.scancodes]
0x70702 = "KEY_F6" # power
0x70701 = "KEY_F5" # source
0x70768 = "KEY_OK" # ok
0x70765 = "KEY_LEFT" # left
0x70762 = "KEY_RIGHT" # right
0x70760 = "KEY_UP" # up
0x70761 = "KEY_DOWN" # down
0x70758 = "KEY_EXIT" # return
0x7072d = "KEY_MENU" # exit
0x7076c = "KEY_POWER" # red - kodi power menu
0x70714 = "KEY_ANGLE" # green - <display> - FullScreen
0x70715 = "KEY_VOLUMEDOWN" # yellow
0x70716 = "KEY_VOLUMEUP" # blue
0x70746 = "KEY_STOP" # stop
0x70747 = "KEY_PLAY" # play
0x7074a = "KEY_PAUSE" # pause
0x70748 = "KEY_FASTFORWARD" # forward
0x70745 = "KEY_REWIND" # rewind
0x70704 = "KEY_1" # 1
0x70705 = "KEY_2" # 2
0x70706 = "KEY_3" # 3
0x70708 = "KEY_4" # 4
0x70709 = "KEY_5" # 5
0x7070a = "KEY_6" # 6
0x7070c = "KEY_7" # 7
0x7070d = "KEY_8" # 8
0x7070e = "KEY_9" # 9
0x70711 = "KEY_0" # 0
0x7071a = "KEY_F5" # menu
0x7074b = "KEY_F5" # tools
0x7071f = "KEY_TITLE" # info - <title>
#0x7072c = "" # ttx/mix
#0x70713 = "" # pre-ch
0x7074f = "KEY_EPG" # guide
0x7076b = "KEY_TUNER" # ch list - <livetv> - ActivateWindow(TVChannels)
0x70725 = "KEY_SUBTITLE" # ad/subt.
0x7073f = "KEY_F5" # e-manual
0x7078c = "KEY_F5" # media.p
